### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by ozindfw** [Jerryj1127/Redgifs-Downloader-Extension#1]
I downloaded unzipped it.  I've confirmed that chrome/icons/icon16.png is present and loadable. I get:

File Error
Could not load icon 'icons/icon16.png' specified in 'icons'.
Could not load manifest.

I'm not sure where to look for a solution.

**Comment by Jerryj1127** [comment]
Hey @ozindfw , sounds like it is an issue with the chrome browser. Can you close all the instances of chrome and try loading it again.

Also verify that your chrome is up to date.
